# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Install dependencies
      run: go mod download

    - name: Build app
      run: cd cmd/ && go build -o app

    - name: Start app in background
      run: |
        ./app &
        echo $! > app.pid
        sleep 3 # Espera a que la app arranque
      working-directory: ./cmd

    - name: Wait for app to be ready
      run: |
        for i in {1..30}; do
          if curl -s http://localhost:8080/healthz > /dev/null; then
            echo "App is up!"
            break
          fi
          echo "Waiting for app..."
          sleep 1
        done

    - name: Run tests
      run: go test ./...

    - name: Stop app
      if: always()
      run: |
        kill $(cat app.pid) || true
