# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Install dependencies
      run: go mod download

    - name: Build app
      run: cd cmd/ && go build -o app

    - name: Start app in background
      run: |
        cd cmd/ && ./app &
        echo $! > app.pid
      working-directory: ./cmd
      env:
        PORT: 8080

    - name: Wait for app to be ready
      run: |
        for i in {1..10}; do
          nc -z localhost 8080 && echo "App is up!" && exit 0
          echo "Waiting for app..."
          sleep 1
        done
        echo "App did not start in time" && exit 1

    - name: Run tests
      run: go test ./...
      env:
        PORT: 8080

    - name: Stop app
      if: always()
      run: |
        kill $(cat app.pid) || true
      working-directory: ./cmd
